const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    CHANGE_OTP_CODE_MODAL: 'CHANGE_OTP_CODE_MODAL',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    FACEBOOK_SIGN_IN_START: 'FACEBOOK_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    UPDATE_INVITATIONS: 'UPDATE_INVITATIONS',
    UPDATE_DP_START: 'UPDATE_DP_START',
    UPDATE_DP_SUCCESS: 'UPDATE_DP_SUCCESS',
    UPDATE_DP_FAILURE: 'UPDATE_DP_FAILURE',
    REQUEST_PHONE_VERIFICATION_START: 'REQUEST_PHONE_VERIFICATION_START',
    REQUEST_PHONE_VERIFICATION_SUCCESS: 'REQUEST_PHONE_VERIFICATION_SUCCESS',
    REQUEST_PHONE_VERIFICATION_FAILURE: 'REQUEST_PHONE_VERIFICATION_FAILURE',
    GET_RESULT_PHONE_VERIFICATION_START: 'GET_RESULT_PHONE_VERIFICATION_START',
    GET_RESULT_PHONE_VERIFICATION_SUCCESS:
        'GET_RESULT_PHONE_VERIFICATION_SUCCESS',
    GET_RESULT_PHONE_VERIFICATION_FAILURE:
        'GET_RESULT_PHONE_VERIFICATION_FAILURE',
};

export default UserActionTypes;
